spring.application.name=Hopital

# Connexion base de données (valeurs injectées via variables d'environnement)
spring.datasource.url=jdbc:postgresql://dpg-da3p9ue7bikc73bhojug-a.oregon-postgres.render.com:5432/hopital_a7kx?sslmode=require
spring.datasource.username=hopital_a7kx_user
spring.datasource.password=WU5wdf4n1x5y3p08CbAPjtWLs0gCLsHa
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Port dynamique fourni par Render
server.port=${PORT:8080}
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.validation-timeout=10000
spring.datasource.hikari.maximum-pool-size=5